# Generated by Django 4.2.7 on 2024-01-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_ranking'),
        ('demonlist', '0037_alter_demon_all_stars_alter_demon_atmosphere_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500)),
                ('position', models.IntegerField()),
                ('change_number', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down')], max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('demons', models.ManyToManyField(blank=True, to='demonlist.demon')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
