# Generated by Django 4.2.7 on 2024-01-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0038_roulette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roulette',
            old_name='change_number',
            new_name='max_demons',
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='position',
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='reason',
        ),
    ]
