# Generated by Django 4.2.7 on 2024-01-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0039_rename_change_number_roulette_max_demons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='level_id_ldm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
